name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_KEY }}" > ~/.ssh/lightsail
        chmod 600 ~/.ssh/lightsail
        echo -e "Host lightsail\n  HostName dinelynk.com\n  User ubuntu\n  IdentityFile ~/.ssh/lightsail\n  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Force Pull Latest Code from GitHub on Lightsail and Reboot
      run: |
        ssh lightsail "
          cd ~/workflow-wiz-ai && \
          git fetch origin main && \
          git reset --hard origin/main && \
          npm install --omit=dev && \
          npm run build && \
          pm2 delete workflow-wiz || true && \
          pm2 start npm --name workflow-wiz -- run preview && \
          pm2 save && \
          (sleep 10 && sudo reboot) &
        "    
