name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_KEY }}" > ~/.ssh/lightsail
          chmod 600 ~/.ssh/lightsail
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/lightsail

      - name: SSH into Lightsail and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@dinelynk.com << 'EOF'
            cd ~/workflow-wiz-ai
            git pull origin main
            pm2 restart workflow-ai
          EOF
