name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_KEY }}" > ~/.ssh/lightsail
        chmod 600 ~/.ssh/lightsail
        cat <<'CONF' >> ~/.ssh/config
        Host lightsail
          HostName ai.redzen.cloud
          User ubuntu
          IdentityFile ~/.ssh/lightsail
          StrictHostKeyChecking no
        CONF

    - name: Build & reload on server
      run: |
        ssh lightsail <<'EOF'
          set -e
          cd ~/workflow-wiz-ai
          git fetch origin main
          git reset --hard origin/main

          # Install deps & build
          npm ci --quiet
          npm run build

          # Restart the already-defined PM2 app (start-serve.sh using port 4173)
          pm2 reload workflow-wiz || pm2 start ./start-serve.sh --name workflow-wiz
          pm2 save
        EOF
